blank_issues_enabled: false
contact_links:
  - name: 📚 View Documentation
    url: https://github.com/astettnerPTG/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Learn how to develop and work with the High School Management System
  - name: 🆘 Emergency Support
    url: https://github.com/astettnerPTG/skills-expand-your-team-with-copilot/discussions
    about: For urgent issues that need immediate attention, start a discussion