name: UI/Feature Improvement
description: Request improvements to the user interface or new features
title: "Improvement: [BRIEF DESCRIPTION]"
labels: ["enhancement", "ui", "feature", "teacher-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## UI/Feature Improvement Request
        
        Please fill out this form to request improvements to the user interface or new features for the Mergington High School activity management system.
        
        **Instructions for Copilot Coding Agent:**
        This request asks for enhancements to improve the user experience or add new functionality. Focus on the specific improvement requested.

  - type: dropdown
    id: improvement-type
    attributes:
      label: Type of Improvement
      description: What kind of improvement is this?
      options:
        - User Interface (colors, layout, styling)
        - New Feature (add functionality)
        - User Experience (make easier to use)
        - Performance (make faster)
        - Accessibility (easier for all users)
        - Mobile/Responsive (better on phones/tablets)
        - Other (specify in description)
    validations:
      required: true

  - type: textarea
    id: current-situation
    attributes:
      label: Current Situation
      description: What is the current state that needs improvement?
      placeholder: "e.g., The activity cards are hard to read, there's no way to search activities, login form is confusing"
    validations:
      required: true

  - type: textarea
    id: desired-improvement
    attributes:
      label: Desired Improvement
      description: What specific improvement would you like to see?
      placeholder: "e.g., Make activity cards more colorful and easier to read, add a search box to find activities, simplify the login process"
    validations:
      required: true

  - type: textarea
    id: user-benefit
    attributes:
      label: How will this help users?
      description: What problem will this solve or how will it make things better?
      placeholder: "e.g., Teachers will be able to find activities faster, students will have better information about activities"
    validations:
      required: true

  - type: dropdown
    id: affected-users
    attributes:
      label: Who will benefit from this improvement?
      description: Select all that apply
      multiple: true
      options:
        - Teachers
        - Students
        - School Administrators
        - Parents
        - All Users

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this improvement?
      options:
        - High - Very important for daily use
        - Medium - Would be nice to have
        - Low - Not urgent but would be helpful
    validations:
      required: true

  - type: textarea
    id: specific-requirements
    attributes:
      label: Specific Requirements
      description: Any specific requirements or constraints?
      placeholder: "e.g., Must work on mobile devices, should match school colors, needs to be accessible for screen readers"

  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested Solution (optional)
      description: If you have ideas for how to implement this, share them here
      placeholder: "e.g., Add a search input box at the top of the activities list, use CSS Grid for better layout"

  - type: markdown
    attributes:
      value: |
        ## Acceptance Criteria
        
        **For the Copilot Coding Agent - this task is complete when:**
        - [ ] Improvement is implemented according to the specifications
        - [ ] Change enhances user experience without breaking existing functionality
        - [ ] UI changes are consistent with the existing design style
        - [ ] Feature works across different browsers and devices
        - [ ] Code changes are clean and maintainable
        - [ ] No accessibility issues are introduced
        - [ ] Changes are tested thoroughly
        
        ## Implementation Hints
        
        **For UI improvements:**
        - Modify CSS in `src/static/style.css` (if exists) or add styles to `src/static/index.html`
        - Ensure changes are responsive and work on mobile devices
        - Use consistent color scheme and typography
        - Test on different screen sizes and browsers
        
        **For new features:**
        - Add frontend JavaScript to `src/static/app.js`
        - Add backend endpoints to appropriate router files if needed
        - Update HTML structure in `src/static/index.html` if needed
        - Consider database changes in `src/backend/database.py` if required
        
        **For user experience improvements:**
        - Focus on making common tasks easier and faster
        - Provide clear feedback to users
        - Handle error states gracefully
        - Add loading indicators for slow operations
        
        ## Context & Limitations
        
        - Frontend uses vanilla JavaScript (no frameworks like React/Vue)
        - Backend is FastAPI with MongoDB database
        - System should work without JavaScript frameworks
        - Keep design simple and functional for school environment
        - Consider that teachers may not be tech-savvy
        - Changes should not require extensive server configuration
        - Mobile-friendly design is important for modern usage
        - Accessibility should be considered for all users